version: '3'
services:
  express-app:
    build:
      context: ..
      args: 
      - NODE_ENV=production
    ports:
      - '8000:8000'
    command: npm start
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: irfan
      MONGO_INITDB_ROOT_PASSWORD: asdf
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: