version: '3'
services:
  express-app:
    build:
      context: ..
      args: 
      - NODE_ENV=production
    image: express-app-image-test
    ports:
    - '8000:8000'
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: irfan
      MONGO_INITDB_ROOT_PASSWORD: asdf
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: