version: '3'
services:
  express-app:
    build:
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
      - MONGO_USER=irfan
      - MONGO_PASSWORD=asdf
    volumes:
      - ../:/app
      - ./app/node_modules
    command: npm run dev
