apiVersion: v1
kind: Service
metadata:
  name: learn-kubernetes-service
spec:
  selector:
    app: express-app-deployment
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer