apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
      - name: express-app-image
        imagePullPolicy: IfNotPresent
        image: express-apps-image
        env:
          - name: TEST_VAL
            valueFrom:
              secretKeyRef: 
                name: express-app-secret
                key: test-env
          - name : MONGO_URL_TEST
            valueFrom:
              configMapKeyRef:
                name: express-app-config
                key: mongo-url
              
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: registry-secrets
