apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db-app
  template:
    metadata:
      labels:
        app: mongo-db-app
    spec:
      containers:
      - name: mongo-db-app-image
        imagePullPolicy: IfNotPresent
        image: mongo
        ports:
        - containerPort: 27017
